name: Deploy Master Bulk Data Fuel App (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy App on Server
        run: |
          cd /data/development/master-data-bulk
          git pull origin main
        shell: bash

